<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Newtonsoft.Json" />
    <!--<PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />-->
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
  </ItemGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="ArchitectureTests" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Database\Migrations\" />
  </ItemGroup>

</Project>
