// <auto-generated />
using System;
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250725152254_InitialCreateAndSeed")]
    partial class InitialCreateAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Animals.Bird", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("name");

                    b.Property<long>("WingspanInCentimeters")
                        .HasColumnType("bigint")
                        .HasColumnName("Wingspan");

                    b.HasKey("Id")
                        .HasName("pk_birds");

                    b.ToTable("birds", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1e1e1e1-1111-1111-1111-111111111111"),
                            Name = "Eagle",
                            WingspanInCentimeters = 200L
                        },
                        new
                        {
                            Id = new Guid("b2e2e2e2-2222-2222-2222-222222222222"),
                            Name = "Parrot",
                            WingspanInCentimeters = 25L
                        },
                        new
                        {
                            Id = new Guid("c3e3e3e3-3333-3333-3333-333333333333"),
                            Name = "Penguin",
                            WingspanInCentimeters = 30L
                        });
                });

            modelBuilder.Entity("Domain.Animals.Cat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("colour");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cats");

                    b.ToTable("cats", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f6e6e6e6-6666-6666-6666-666666666666"),
                            Colour = "Tabby",
                            Name = "Whiskers"
                        },
                        new
                        {
                            Id = new Guid("a7e7e7e7-7777-7777-7777-777777777777"),
                            Colour = "Black and White",
                            Name = "Toby"
                        });
                });

            modelBuilder.Entity("Domain.Animals.Dog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Colour1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("colour1");

                    b.Property<string>("Colour2")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("colour2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("name");

                    b.Property<string>("Pattern")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("pattern");

                    b.HasKey("Id")
                        .HasName("pk_dogs");

                    b.ToTable("dogs", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e4e4e4-4444-4444-4444-444444444444"),
                            Colour1 = "Brown",
                            Name = "Rover"
                        },
                        new
                        {
                            Id = new Guid("e5e5e5e5-5555-5555-5555-555555555555"),
                            Colour1 = "White",
                            Colour2 = "Black",
                            Name = "Spot",
                            Pattern = "Spots"
                        });
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8000ba35-6cf7-4aef-90f7-097f8f6a3b13"),
                            Email = "a@b.com",
                            FirstName = "API",
                            LastName = "User",
                            PasswordHash = "BE18F3BE7CD3799DF493F45B9118F3EE4A5BF512A96DC326907257D238B44628-29841CFA820416A7FEFB8CB02C56301B"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
