<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>


  <ItemGroup>
    <Folder Include="Users\" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

</Project>
